# Generated by Django 4.0.4 on 2022-07-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='medico',
        ),
    ]
